Repository SOPT-33RD-APP-NAVERPAY/NaverPay-Android, pull requests merged in 2023-11, with the labels that each got.

#4 [ADD] : Set up color system
  app/src/main/res/drawable/gradient_bg_gd.xml
  app/src/main/res/drawable/gradient_main_home_cardline.xml
  app/src/main/res/drawable/gradient_sub_gd.xml
  app/src/main/res/drawable/gradient_sub_gd1.xml
  app/src/main/res/drawable/gradient_sub_gd2.xml
  app/src/main/res/drawable/gradient_sub_gd3.xml
  app/src/main/res/drawable/gradient_sub_gd4.xml
  app/src/main/res/values/colors.xml
Labels: ➕ [ADD], 🐸 준서

#7 Feature/color setting
  app/src/main/res/values/colors.xml
Labels: ➕ [ADD], 🐸 준서

#11 [feature/benefit] Benefit View 화면 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dosopt/naverpay/domain/model/benefit/Brand.kt
  app/src/main/java/com/dosopt/naverpay/domain/model/benefit/User.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/BenefitFragment.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/BenefitViewModel.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/adapter/AdmobAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/adapter/CardMenuAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/adapter/ImmediateBrandAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/adapter/PopularBrandAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/decorator/CardMenuItemDecoration.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/decorator/DividerItemDecoration.kt
  app/src/main/res/drawable-xhdpi/img_ad_paris.png
  app/src/main/res/drawable-xhdpi/img_ad_pica.png
  app/src/main/res/drawable-xhdpi/img_ad_tj.png
  app/src/main/res/drawable-xhdpi/img_benefit_btn_card_1.png
  app/src/main/res/drawable-xhdpi/img_benefit_btn_card_2.png
  app/src/main/res/drawable-xhdpi/img_benefit_btn_card_3.png
  app/src/main/res/drawable-xhdpi/img_benefit_btn_card_4.png
  app/src/main/res/drawable-xxhdpi/img_ad_paris.png
  app/src/main/res/drawable-xxhdpi/img_ad_pica.png
  app/src/main/res/drawable-xxhdpi/img_ad_tj.png
  app/src/main/res/drawable-xxhdpi/img_benefit_btn_card_1.png
  app/src/main/res/drawable-xxhdpi/img_benefit_btn_card_2.png
  app/src/main/res/drawable-xxhdpi/img_benefit_btn_card_3.png
  app/src/main/res/drawable-xxhdpi/img_benefit_btn_card_4.png
  app/src/main/res/drawable/ic_alert.xml
  app/src/main/res/drawable/ic_like_off.xml
  app/src/main/res/drawable/ic_like_on.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_offarrow.xml
  app/src/main/res/drawable/ic_point_menu_1_off.xml
  app/src/main/res/drawable/ic_point_menu_1_on.xml
  app/src/main/res/drawable/ic_point_menu_2_off.xml
  app/src/main/res/drawable/ic_point_menu_2_on.xml
  app/src/main/res/drawable/ic_point_menu_3_off.xml
  app/src/main/res/drawable/ic_point_menu_3_on.xml
  app/src/main/res/drawable/ic_point_menu_4_off.xml
  app/src/main/res/drawable/ic_point_menu_4_on.xml
  app/src/main/res/drawable/ic_point_menu_5_off.xml
  app/src/main/res/drawable/ic_point_menu_5_on.xml
  app/src/main/res/drawable/ic_pointarrow.xml
  app/src/main/res/drawable/ic_qnaarrow.xml
  app/src/main/res/drawable/ic_round_menu.xml
  app/src/main/res/drawable/img_ad_paris.png
  app/src/main/res/drawable/img_ad_pica.png
  app/src/main/res/drawable/img_ad_tj.png
  app/src/main/res/drawable/img_benefit_btn_card_1.png
  app/src/main/res/drawable/img_benefit_btn_card_2.png
  app/src/main/res/drawable/img_benefit_btn_card_3.png
  app/src/main/res/drawable/img_benefit_btn_card_4.png
  app/src/main/res/drawable/rectangle_palegreen2_radius_100.xml
  app/src/main/res/drawable/rectangle_palegreen_radius_10.xml
  app/src/main/res/drawable/rectangle_white_radius_12.xml
  app/src/main/res/layout/fragment_benefit.xml
  app/src/main/res/layout/item_benefit_admob.xml
  app/src/main/res/layout/item_benefit_card.xml
  app/src/main/res/layout/item_benefit_immediate_brand.xml
  app/src/main/res/layout/item_benefit_popular_brand.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐯 재원

#12 [feature/home] Home View 화면 구성
  app/src/main/java/com/dosopt/naverpay/domain/home/HomeDataClass.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/HomeFragment.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/adapter/BrandAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/adapter/CardAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/adapter/EventAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/decorator/BrandItemDecoration.kt
  app/src/main/res/color/selc_bottom_nav_item.xml
  app/src/main/res/drawable/circle_bg_white.xml
  app/src/main/res/drawable/gradient_linear_gd.xml
  app/src/main/res/drawable/ic_card_indicator.xml
  app/src/main/res/drawable/ic_home_add_card.xml
  app/src/main/res/drawable/ic_home_arrow_gray.xml
  app/src/main/res/drawable/ic_home_arrow_white.xml
  app/src/main/res/drawable/ic_home_map.xml
  app/src/main/res/drawable/ic_home_menu.xml
  app/src/main/res/drawable/ic_home_notice.xml
  app/src/main/res/drawable/ic_home_uv.xml
  app/src/main/res/drawable/img_brand_1.png
  app/src/main/res/drawable/img_brand_2.png
  app/src/main/res/drawable/img_brand_3.png
  app/src/main/res/drawable/img_brand_4.png
  app/src/main/res/drawable/img_brand_blank.png
  app/src/main/res/drawable/img_card_1.png
  app/src/main/res/drawable/img_card_2.png
  app/src/main/res/drawable/img_card_3.png
  app/src/main/res/drawable/img_card_add.png
  app/src/main/res/drawable/img_card_blank.png
  app/src/main/res/drawable/img_event_1.png
  app/src/main/res/drawable/img_event_2.png
  app/src/main/res/drawable/img_event_3.png
  app/src/main/res/drawable/img_logo.xml
  app/src/main/res/drawable/img_logo_gs25.png
  app/src/main/res/drawable/img_recent_blank.png
  app/src/main/res/drawable/rectangle_bg_transparent_gray_radius_4.xml
  app/src/main/res/drawable/rectangle_bg_transparent_green_radius_4.xml
  app/src/main/res/drawable/rectangle_bg_white_radius_6.xml
  app/src/main/res/drawable/rectangle_sub_gd_radius_10.xml
  app/src/main/res/drawable/rectangle_transparent_radius_6.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_brand.xml
  app/src/main/res/layout/item_card_deselected.xml
  app/src/main/res/layout/item_card_selected.xml
  app/src/main/res/layout/item_event.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], ➕ [ADD], 🔨 [FIX], 🛠️ [CHORE], ♻️ [REFACTOR], 🐸 준서

#13 [feature/place] Place View 화면 구성
  app/build.gradle
  app/src/main/java/com/dosopt/naverpay/domain/place/PlaceBrandList.kt
  app/src/main/java/com/dosopt/naverpay/domain/place/PlaceNearbyplaceList.kt
  app/src/main/java/com/dosopt/naverpay/domain/place/PlaceOnsitePaymentList.kt
  app/src/main/java/com/dosopt/naverpay/domain/place/PlaceUser.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/MainActivity.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/place/PlaceFragment.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/place/PlaceNearbyAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/place/PlacePaymentAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/place/PlaceRecommendAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/place/PlaceViewModel.kt
  app/src/main/res/drawable/ic_android_black_24dp.xml
  app/src/main/res/drawable/ic_place_btn_x.xml
  app/src/main/res/drawable/ic_place_map.xml
  app/src/main/res/drawable/img_place_cu.png
  app/src/main/res/drawable/img_place_cu2.png
  app/src/main/res/drawable/img_place_cu3.png
  app/src/main/res/drawable/logo_pay.xml
  app/src/main/res/drawable/rectangle_black_radius_20.xml
  app/src/main/res/drawable/rectangle_green_radius_20.xml
  app/src/main/res/drawable/selc_place_text_click_dome.xml
  app/src/main/res/drawable/selc_place_text_click_inter.xml
  app/src/main/res/drawable/shape_radius_10.xml
  app/src/main/res/drawable/shape_radius_52.xml
  app/src/main/res/layout/fragment_place.xml
  app/src/main/res/layout/item_place_nearby.xml
  app/src/main/res/layout/item_place_payment.xml
  app/src/main/res/layout/item_place_recommend.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearances.xml
Labels: ⭐ [FEAT], ➕ [ADD], 🐹 민회

#14 [feature/point] Point View 화면 구성
  app/src/main/java/com/dosopt/naverpay/ui/main/MainActivity.kt
  app/src/main/res/drawable-xhdpi/ic_point_benefit.png
  app/src/main/res/drawable-xxhdpi/ic_point_benefit.png
  app/src/main/res/drawable/ic_point_benefit.png
  app/src/main/res/drawable/ic_point_buy.xml
  app/src/main/res/drawable/ic_point_convert.xml
  app/src/main/res/drawable/ic_point_delete.xml
  app/src/main/res/drawable/ic_point_gift.xml
  app/src/main/res/drawable/ic_point_haeader_logo.xml
  app/src/main/res/drawable/ic_point_help.xml
  app/src/main/res/drawable/ic_point_month.xml
  app/src/main/res/drawable/ic_point_month_left.xml
  app/src/main/res/drawable/ic_point_month_right.xml
  app/src/main/res/drawable/ic_point_smarrow.xml
  app/src/main/res/drawable/ic_point_up_arrow.xml
  app/src/main/res/drawable/img_point_banner.xml
  app/src/main/res/drawable/img_point_rv_menu.xml
  app/src/main/res/drawable/rectangle_garph_review_radius_104.xml
  app/src/main/res/drawable/rectangle_sub_darkgreen_radius_9.xml
  app/src/main/res/drawable/rectangle_white_radius_12_border_1.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/item_point_reward.xml
Labels: ⭐ [FEAT], 🐯 재원

#16 [feature/point] API 서비스 연결하기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dosopt/naverpay/network/ApiFactory.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/BaseResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/BenefitResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/DtoDummy.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/HomeResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/LikeResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/PlaceResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/PointResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/RecommendResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/service/NaverPayService.kt
  app/src/main/java/com/dosopt/naverpay/network/service/ServiceDummy.kt
Labels: ⭐ [FEAT], 🐸 준서

#19 [feature/home] Home View API 서비스 연결
  app/src/main/java/com/dosopt/naverpay/domain/model/home/CardInfo.kt
  app/src/main/java/com/dosopt/naverpay/domain/model/home/EventInfo.kt
  app/src/main/java/com/dosopt/naverpay/domain/model/home/HomeDataClass.kt
  app/src/main/java/com/dosopt/naverpay/network/dto/HomeResponse.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/MainActivity.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/HomeFragment.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/adapter/BrandAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/adapter/CardAdapter.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/home/adapter/EventAdapter.kt
  app/src/main/res/drawable/img_brand_1.png
  app/src/main/res/drawable/img_brand_2.png
  app/src/main/res/drawable/img_brand_3.png
  app/src/main/res/drawable/img_brand_4.png
  app/src/main/res/drawable/img_card_blank.png
  app/src/main/res/drawable/img_recent_blank.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_brand.xml
  app/src/main/res/layout/item_home_card_deselected.xml
  app/src/main/res/layout/item_home_card_selected.xml
  app/src/main/res/layout/item_home_event.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐸 준서

#22 [feature/ benefit] Benefit View API 서비스 연결
  app/src/main/java/com/dosopt/naverpay/network/dto/BenefitResponse.kt
  app/src/main/java/com/dosopt/naverpay/network/service/NaverPayService.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/BenefitFragment.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/BenefitViewModel.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/adapter/PopularBrandAdapter.kt
  app/src/main/res/layout/fragment_benefit.xml
  app/src/main/res/layout/item_benefit_immediate_brand.xml
  app/src/main/res/layout/item_benefit_popular_brand.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐯 재원

#27 [Feature/link] fragment 연결 작업 및 기타 완료
  app/src/main/java/com/dosopt/naverpay/ui/main/benefit/BenefitFragment.kt
  app/src/main/java/com/dosopt/naverpay/ui/main/place/PlaceFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐯 재원
